import type { PlaygroundLabels, PlaygroundLocale } from './types'

const labelsByLocale: Record<PlaygroundLocale, PlaygroundLabels> = {
  en: {
    run: 'Run',
    rerun: 'Rerun',
    starting: 'Starting…',
    render: 'Render',
    runAll: 'Run all',
    interrupt: 'Interrupt',
    savePoint: 'Save point',
    returnToPoint: 'Return',
    addFrame: 'Add frame',
    exportGif: 'Export GIF',
    resetSandbox: 'Reset sandbox',
    restoreExample: 'Restore example',
    resetExample: 'Reset example',
    importFiles: 'Import files',
    importFolder: 'Import folder',
    restartSandbox: 'Restart sandbox',
    more: 'More',
    moreActions: 'More actions',
    importLocally: 'Import locally',
    cancel: 'Cancel',
    resetSandboxTitle: 'Clear sandbox state while keeping the edited cell source',
    restoreExampleTitle: 'Restore the original example source and clear sandbox state',
    play: 'Play',
    pause: 'Pause',
    step: 'Step',
    resetView: 'Reset view',
    settings: 'Settings',
    mouseSensitivity: 'Mouse',
    moveSpeed: 'Speed',
    fieldOfView: 'FOV',
    back: 'Back',
    backToCallerTitle: 'Back to caller (Alt+Left)',
    commandOutputs: 'Command outputs',
    structuredResult: 'Structured result',
    showMoreOutputs: 'Show more ({count} remaining)',
  },
  'zh-CN': {
    run: '运行',
    rerun: '重新运行',
    starting: '正在启动…',
    render: '渲染',
    runAll: '全部运行',
    interrupt: '中断',
    savePoint: '保存点',
    returnToPoint: '返回保存点',
    addFrame: '添加帧',
    exportGif: '导出 GIF',
    resetSandbox: '重置沙盒',
    restoreExample: '恢复示例',
    resetExample: '重置示例',
    importFiles: '导入文件',
    importFolder: '导入文件夹',
    restartSandbox: '重启沙盒',
    more: '更多',
    moreActions: '更多操作',
    importLocally: '本地导入',
    cancel: '取消',
    resetSandboxTitle: '清除沙盒状态，但保留已编辑的单元格源码',
    restoreExampleTitle: '恢复原始示例源码并清除沙盒状态',
    play: '播放',
    pause: '暂停',
    step: '单步执行',
    resetView: '重置视角',
    settings: '设置',
    mouseSensitivity: '鼠标灵敏度',
    moveSpeed: '移动速度',
    fieldOfView: '视野',
    back: '返回',
    backToCallerTitle: '返回调用方（Alt+左方向键）',
    commandOutputs: '命令输出',
    structuredResult: '结构化结果',
    showMoreOutputs: '显示更多（剩余 {count} 项）',
  },
}

export function resolvePlaygroundLabels(
  locale: PlaygroundLocale,
  overrides: Partial<PlaygroundLabels>,
): PlaygroundLabels {
  return { ...labelsByLocale[locale], ...overrides }
}
